# Development environment configuration
cab-booking-service:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cab_booking_dev_db
      username: dev_cab_user
      password: dev_cab_password

cab-fare-service:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cab_fare_dev_db
      username: dev_fare_user
      password: dev_fare_password
