# Default configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/default_db
    username: root
    password: password

# Service-specific configurations
cab-booking-service:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cab_booking_db
      username: cab_user
      password: cab_password

cab-fare-service:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cab_fare_db
      username: fare_user
      password: fare_password
